
import React from 'react';
import { Sparkles, Brain, Lightbulb, Code, FlaskConical, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import Layout from '@/components/layout/Layout';
import GradientButton from '@/components/ui/GradientButton';
import FeatureCard from '@/components/common/FeatureCard';

const Index = () => {
  return (
    <Layout>
      {/* Hero Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center">
            <div className="md:w-1/2 text-center md:text-left mb-10 md:mb-0">
              <div className="inline-flex items-center bg-muted px-4 py-2 rounded-full mb-6">
                <Sparkles className="h-4 w-4 text-primary mr-2" />
                <span className="text-sm font-medium">Powered by Llama 3</span>
              </div>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-4">
                Learn anything with AI
                <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent"> explanations</span>
              </h1>
              <p className="text-xl text-foreground/70 mb-8 max-w-lg mx-auto md:mx-0">
                Simple explanations, real-world analogies, and code examples for any topic - all generated by AI.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center md:justify-start">
                <Link to="/ask">
                  <GradientButton size="lg" className="text-base">
                    Start Exploring
                  </GradientButton>
                </Link>
                <Link to="/library">
                  <GradientButton variant="secondary" size="lg" className="text-base">
                    Browse Examples
                  </GradientButton>
                </Link>
              </div>
            </div>
            
            <div className="md:w-1/2 relative">
              <div className="w-full h-80 lg:h-96 relative">
                <div className="absolute inset-0 bg-gradient-radial from-purple/20 to-transparent dark:from-purple/10 rounded-full blur-3xl"></div>
                <div className="relative z-10 w-full h-full flex items-center justify-center">
                  {/* Brain animation or illustration could go here */}
                  <div className="w-52 h-52 bg-gradient-candy rounded-full flex items-center justify-center animate-float">
                    <Brain className="w-24 h-24 text-white" />
                  </div>
                  
                  {/* Floating elements */}
                  <div className="absolute top-10 left-10 glass-card px-5 py-3 animate-float" style={{ animationDelay: '0.5s' }}>
                    <p className="text-sm font-medium">What is quantum computing?</p>
                  </div>
                  <div className="absolute bottom-10 right-10 glass-card px-5 py-3 animate-float" style={{ animationDelay: '1s' }}>
                    <p className="text-sm font-medium">Explain blockchain like I'm 5</p>
                  </div>
                  <div className="absolute bottom-32 left-5 glass-card px-5 py-3 animate-float" style={{ animationDelay: '1.5s' }}>
                    <p className="text-sm font-medium">How does React work?</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-16 bg-muted/50">
        <div className="container mx-auto px-4">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <h2 className="text-3xl font-bold mb-4">What can ExplainMe do?</h2>
            <p className="text-lg text-foreground/70">
              Our AI-powered learning assistant helps you understand any topic with clear explanations and practical examples.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <FeatureCard
              title="AI Explanations"
              description="Get easy-to-understand explanations for any concept, tailored to your level."
              icon={Brain}
            />
            <FeatureCard
              title="Real-World Analogies"
              description="Understand complex topics through relatable analogies and examples."
              icon={Lightbulb}
            />
            <FeatureCard
              title="Code Snippets"
              description="Learn programming concepts with relevant code examples across languages."
              icon={Code}
            />
            <FeatureCard
              title="Interactive Quizzes"
              description="Test your knowledge with AI-generated quizzes based on saved material."
              icon={FlaskConical}
            />
            <FeatureCard
              title="Flashcard Learning"
              description="Review concepts with dynamic flashcards created from your saved explanations."
              icon={Lightbulb}
            />
            <FeatureCard
              title="Collaborative Study"
              description="Join study rooms to learn together with friends in real-time."
              icon={Users}
            />
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="glass-card p-8 md:p-12 text-center">
            <h2 className="text-3xl font-bold mb-4">Ready to learn smarter?</h2>
            <p className="text-lg text-foreground/70 mb-8 max-w-2xl mx-auto">
              Stop struggling with complex topics. Let AI help you understand anything with simple explanations and examples.
            </p>
            <Link to="/ask">
              <GradientButton size="lg" className="text-base">
                Try ExplainMe Now
              </GradientButton>
            </Link>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default Index;
